from PyQt5 import QtCore, QtGui, QtWidgets
import os,sys,sqlite3,smtplib,time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

class Ui_Form(object):
    def __init__(self):
        self.baglantiOlustur()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(857, 644)
        font = QtGui.QFont()
        font.setPointSize(14)
        Form.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblBaslik = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lblBaslik.setFont(font)
        self.lblBaslik.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBaslik.setObjectName("lblBaslik")
        self.verticalLayout_3.addWidget(self.lblBaslik)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtMailListe = QtWidgets.QTextEdit(Form)
        self.txtMailListe.setObjectName("txtMailListe")
        self.verticalLayout.addWidget(self.txtMailListe)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnDosyaAc = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDosyaAc.setFont(font)
        self.btnDosyaAc.setObjectName("btnDosyaAc")
        self.horizontalLayout.addWidget(self.btnDosyaAc)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblKullaniciGirisi = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblKullaniciGirisi.setFont(font)
        self.lblKullaniciGirisi.setAlignment(QtCore.Qt.AlignCenter)
        self.lblKullaniciGirisi.setObjectName("lblKullaniciGirisi")
        self.verticalLayout_2.addWidget(self.lblKullaniciGirisi)
        self.lblLoginAciklama = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblLoginAciklama.setFont(font)
        self.lblLoginAciklama.setText("")
        self.lblLoginAciklama.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLoginAciklama.setObjectName("lblLoginAciklama")
        self.verticalLayout_2.addWidget(self.lblLoginAciklama)
        self.lnKullaniciAdi = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lnKullaniciAdi.setFont(font)
        self.lnKullaniciAdi.setInputMask("")
        self.lnKullaniciAdi.setText("")
        self.lnKullaniciAdi.setObjectName("lnKullaniciAdi")
        self.verticalLayout_2.addWidget(self.lnKullaniciAdi)
        self.lnParola = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lnParola.setFont(font)
        self.lnParola.setText("")
        self.lnParola.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnParola.setReadOnly(False)
        self.lnParola.setObjectName("lnParola")
        self.verticalLayout_2.addWidget(self.lnParola)
        self.btnGiris = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGiris.setFont(font)
        self.btnGiris.setObjectName("btnGiris")
        self.verticalLayout_2.addWidget(self.btnGiris)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.lblMailAciklama = QtWidgets.QLabel(Form)
        self.lblMailAciklama.setObjectName("lblMailAciklama")
        self.verticalLayout_3.addWidget(self.lblMailAciklama)
        self.txtMailMetin = QtWidgets.QTextEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtMailMetin.setFont(font)
        self.txtMailMetin.setObjectName("txtMailMetin")
        self.verticalLayout_3.addWidget(self.txtMailMetin)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnGonder = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGonder.setFont(font)
        self.btnGonder.setObjectName("btnGonder")
        self.horizontalLayout_2.addWidget(self.btnGonder)
        self.lblGonderimAciklama = QtWidgets.QLabel(Form)
        self.lblGonderimAciklama.setText("")
        self.lblGonderimAciklama.setObjectName("lblGonderimAciklama")
        self.horizontalLayout_2.addWidget(self.lblGonderimAciklama)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.txtMailMetin.raise_()
        self.lblBaslik.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.lblMailAciklama.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.btnDosyaAc.clicked.connect(self.dosyaAc)
        self.btnGiris.clicked.connect(self.login)
        self.btnGonder.clicked.connect(self.mailGonder)
    def mailHazirlaGonder(self):
        mailGonder(mehmet,mehmetcan.c@gmail.com,"Mail Deneme")
    def mailGonder(self):
        if self.login():
            self.lblGonderimAciklama.setText("Mail Göndermeye Hazırsınız!")
            bilgiler=self.txtMailListe.toPlainText()
            bilgiler=bilgiler.replace("\n",",")
            bilgiler=bilgiler.split(",")
            for i in range(0,len(bilgiler)-1,2):
                bilgiler[i]=bilgiler[i].rstrip(" ")
                bilgiler[i] = bilgiler[i].lstrip(" ")
                bilgiler[i+1] = bilgiler[i+1].rstrip(" ")#kişi Adı Soyadı
                bilgiler[i+1] = bilgiler[i+1].lstrip(" ")#mail adresi

                mesaj = MIMEMultipart()
                mesaj["From"] = "mehmetcan.c@gmail.com"
                mesaj["To"] = bilgiler[i+1]
                mesaj["Subject"] = "Otomatik Smtp Mail Gönderme"
                yazi = self.txtMailMetin.toPlainText().format(bilgiler[i])
                mesaj_govdesi = MIMEText(yazi, "plain")
                mesaj.attach(mesaj_govdesi)
                try:
                    mail = smtplib.SMTP("smtp.gmail.com", 587)
                    mail.ehlo()
                    mail.starttls()
                    mail.login("mehmetcan.c@gmail.com", "can2HN384")
                    mail.sendmail(mesaj["From"], mesaj["To"], mesaj.as_string())
                    self.lblGonderimAciklama.setText("Mail '{}' Adresine Başarıyla Gönderildi....".format(bilgiler[i+1]))
                    time.time(2)
                    mail.close()
                except:
                    self.lblGonderimAciklama.setText("'{}' Adresine Gönderilirken Bir sorun oluştu!".format(bilgiler[i+1]))
            self.lblGonderimAciklama.setText("Mail Gönderimi Tamamlandı!..")
        else:
            self.lblGonderimAciklama.setText("Önce giriş Yapmalısınız!")

    def dosyaAc(self):
        dosyaAdi,_=QtWidgets.QFileDialog.getOpenFileName(Form, 'Open File', os.getenv('HOME'))
        with open(dosyaAdi,"r",encoding="utf-8") as file:
            self.txtMailListe.setText(file.read())

    def baglantiOlustur(self):
        baglanti=sqlite3.connect("veritabani.db")
        self.cursor=baglanti.cursor()
        self.cursor.execute("create table if not exists uyeler(kullaniciAdi TEXT,parola TEXT)")
        baglanti.commit()

    def login(self):
        adi=self.lnKullaniciAdi.text()
        par=self.lnParola.text()
        self.cursor.execute("select * from uyeler where kullaniciAdi=? and parola=?",(adi,par))
        data=self.cursor.fetchall()

        if len(data)==0:
            self.lblLoginAciklama.setText("Hatalı Giriş")
            return False
        else:
            self.lblLoginAciklama.setText("Hoşgeldin!\n"+adi)
            return True

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Mail Gönder"))
        self.lblBaslik.setText(_translate("Form", "Otomatik Mail Gönderme Programına Hoşgeldiniz!"))
        self.txtMailListe.setPlaceholderText(_translate("Form", "Mail Listesi adı soyadı, mailadresi@servis.com şeklinde olmalıdır"))
        self.btnDosyaAc.setText(_translate("Form", "Dosya Aç"))
        self.lblKullaniciGirisi.setText(_translate("Form", "Kullanıcı Girişi"))
        self.lnKullaniciAdi.setPlaceholderText(_translate("Form", "Kullanıcı Adı"))
        self.lnParola.setPlaceholderText(_translate("Form", "Parola"))
        self.btnGiris.setText(_translate("Form", "Giriş"))
        self.lblMailAciklama.setText(_translate("Form", "Mailde isim yerine {} sembolünü kullanınız. Sistem kişinin ismini otomatik olarak yazacaktır!"))
        self.btnGonder.setText(_translate("Form", "Gönder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

